In [2]:
import pandas as pd

# Load the two datasets
patient_df = pd.read_csv("../data/data_clinical_patient.txt", sep="\t", comment="#")
sample_df  = pd.read_csv("../data/data_clinical_sample.txt", sep="\t", comment="#")

# Merge them using PATIENT_ID
full_df = patient_df.merge(sample_df, on="PATIENT_ID", how="inner")

# Create the target column
full_df["recurred"] = full_df["RFS_STATUS"].map({"1:Recurred": 1, "0:Not Recurred": 0})

# Show basic information
print(f"Shape: {full_df.shape}")
print(f"\nTarget:\n{full_df['recurred'].value_counts(dropna=False)}")
print(f"\nUnique patients: {full_df['PATIENT_ID'].nunique()}")
print(f"One row per patient: {full_df['PATIENT_ID'].nunique() == len(full_df)}")
print(f"\nMissing values:\n{full_df.isnull().sum()[full_df.isnull().sum() > 0].sort_values(ascending=False)}")

full_df.head()

Shape: (2509, 37)

Target:
recurred
0.0    1486
1.0    1002
NaN      21
Name: count, dtype: int64

Unique patients: 2509
One row per patient: True

Missing values:
THREEGENE                        745
TUMOR_STAGE                      721
LATERALITY                       639
CELLULARITY                      592
BREAST_SURGERY                   554
INTCLUST                         529
HER2_STATUS                      529
RADIO_THERAPY                    529
VITAL_STATUS                     529
CHEMOTHERAPY                     529
INFERRED_MENOPAUSAL_STATE        529
HORMONE_THERAPY                  529
HER2_SNP6                        529
PR_STATUS                        529
CLAUDIN_SUBTYPE                  529
OS_STATUS                        528
OS_MONTHS                        528
LYMPH_NODES_EXAMINED_POSITIVE    266
NPI                              222
TUMOR_SIZE                       149
HISTOLOGICAL_SUBTYPE             135
GRADE                            121
RFS_MONTHS                       121
ER_IHC                            83
ER_STATUS                         40
RFS_STATUS                        21
recurred                          21
AGE_AT_DIAGNOSIS                  11
COHORT                            11
dtype: int64

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,ER_STATUS,HER2_STATUS,GRADE,ONCOTREE_CODE,PR_STATUS,SAMPLE_TYPE,TUMOR_SIZE,TUMOR_STAGE,TMB_NONSYNONYMOUS,recurred
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,Positive,Negative,3.0,IDC,Negative,Primary,22.0,2.0,0.000000,0.0
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,3.0,IDC,Positive,Primary,10.0,1.0,2.615035,0.0
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,2.0,IDC,Positive,Primary,15.0,2.0,2.615035,1.0
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,2.0,MDLC,Positive,Primary,25.0,2.0,1.307518,0.0
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,Positive,Negative,3.0,MDLC,Positive,Primary,40.0,2.0,2.615035,1.0

In [3]:
full_df.head()

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,ER_STATUS,HER2_STATUS,GRADE,ONCOTREE_CODE,PR_STATUS,SAMPLE_TYPE,TUMOR_SIZE,TUMOR_STAGE,TMB_NONSYNONYMOUS,recurred
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,Positive,Negative,3.0,IDC,Negative,Primary,22.0,2.0,0.000000,0.0
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,3.0,IDC,Positive,Primary,10.0,1.0,2.615035,0.0
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,2.0,IDC,Positive,Primary,15.0,2.0,2.615035,1.0
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Positive,Negative,2.0,MDLC,Positive,Primary,25.0,2.0,1.307518,0.0
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,Positive,Negative,3.0,MDLC,Positive,Primary,40.0,2.0,2.615035,1.0

In [4]:
full_df.to_csv("metabric_patient_sample_merged.csv", index=False)
print("Saved!")
print(f"Shape: {full_df.shape}")

Saved!
Shape: (2509, 37)